version: "3"
services:
  web:
    image: ghost:1-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "./content:/var/lib/ghost/content"
    environment:
      - VIRTUAL_HOST=ghost.localhost
      - LETSENCRYPT_HOST=ghost.localhost
      - LETSENCRYPT_EMAIL=admin@ghost.localhost
      - url=http://ghost.localhost
networks:
  default:
    external:
      name: skynet
