version: "3"
services:
  web:
    image: ghost:1-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "./content:/var/lib/ghost/content"
    expose:
      - "2368"
    networks:
      - webnet
    environment:
      - VIRTUAL_HOST=ghost.localhost
      - url=http://ghost.localhost
  proxy:
    image: jwilder/nginx-proxy
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet:
